server.port=${SERVER_PORT:8089}
spring.application.name=rahulverse

spring.datasource.url=jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:rahulverseDB}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:rootpassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# pass variables from .env file
# SERVER_PORT=8089
# DB_HOST=mysql
# DB_PORT=3306
# DB_NAME=your_db_name
# DB_USER=root
# DB_PASSWORD=your_rootpassword
